import {
  BoothSettings,
  CameraFilter,
  DriveConfig,
  LayoutConfig,
  LayoutId,
  WeddingConfig,
  WeddingFramePreset,
} from "./types";

export const DEFAULT_WEDDING_CONFIG: WeddingConfig = {
  brideName: "Isna",
  groomName: "Fadel",
  weddingDate: "04 Oktober 2026",
  venueText: "Rumah Mempelai Wanita",
  hashtag: "#IsnaFadelStory",
  footerText: "The Wedding of Isna & Fadel • 04 Oktober 2026",
};

export const DEFAULT_DRIVE_CONFIG: DriveConfig = {
  appsScriptUrl:
    "https://script.google.com/macros/s/AKfycbwjEdDj58epC0wLH3pHAbzpyaM9d_ab2qYXd-7Yf2da0lxYlEuVQMKxYoozqmPVCmRS/exec",
  driveFolderUrl:
    "https://drive.google.com/drive/folders/1AP-Qy0NhrwDyZn5EuA6zOY5uSzyT4bmV?usp=drive_link",
  autoUpload: true,
};

export const DEFAULT_BOOTH_SETTINGS: BoothSettings = {
  countdownDuration: 3,
  autoResetDuration: 60,
  soundEnabled: true,
  mirrorCamera: true,
  adminPin: "1234",
  defaultPrintCopies: 1,
  kioskFullscreen: false,
};

export const LAYOUTS: LayoutConfig[] = [
  {
    id: "4x2",
    name: "Grid 8 Foto",
    subtitle: "8 jepretan bervariasi",
    rows: 4,
    cols: 2,
    totalPhotos: 8,
    paperSizeLabel: "Cetak 10×15 cm (4R)",
    badge: "Terfavorit",
    aspectRatio: "2/3",
  },
  {
    id: "3x2",
    name: "Grid 6 Foto",
    subtitle: "6 jepretan dua kolom",
    rows: 3,
    cols: 2,
    totalPhotos: 6,
    paperSizeLabel: "Cetak 10×15 cm (4R)",
    badge: "Populer",
    aspectRatio: "2/3",
  },
  {
    id: "2x2",
    name: "Grid 4 Foto",
    subtitle: "4 momen manis persegi",
    rows: 2,
    cols: 2,
    totalPhotos: 4,
    paperSizeLabel: "Cetak 10×15 cm (4R)",
    badge: "Klasik",
    aspectRatio: "1/1",
  },
  {
    id: "3x1",
    name: "Strip 3 Foto",
    subtitle: "Strip vertikal klasik",
    rows: 3,
    cols: 1,
    totalPhotos: 3,
    paperSizeLabel: "Cetak 5×15 cm (2 Strip)",
    badge: "Vintage",
    aspectRatio: "1/3",
  },
  {
    id: "2x1",
    name: "Strip 2 Foto",
    subtitle: "Dua foto format strip",
    rows: 2,
    cols: 1,
    totalPhotos: 2,
    paperSizeLabel: "Cetak 5×15 cm (2 Strip)",
    badge: "Ringkas",
    aspectRatio: "1/2",
  },
  {
    id: "1x1",
    name: "Foto Polaroid",
    subtitle: "Satu foto besar elegan",
    rows: 1,
    cols: 1,
    totalPhotos: 1,
    paperSizeLabel: "Cetak 10×15 cm (4R)",
    badge: "Portrait",
    aspectRatio: "3/4",
  },
];

export const WEDDING_PRESETS: WeddingFramePreset[] = [
  {
    id: "royal_gold",
    name: "Royal Champagne Gold",
    description: "Kemewahan emas kerajaan dengan aksen hangat memikat",
    bgGradient: "linear-gradient(180deg, #16181f 0%, #101217 100%)",
    bgColor: "#12141A",
    borderColor: "#D4AF37",
    accentColor: "#ECC876",
    textColor: "#FFF2D1",
    secondaryTextColor: "#C4A255",
    headerStyle: "ornament",
    previewClass: "border-amber-400/50 bg-stone-900",
  },
  {
    id: "rose_floral",
    name: "Romantic Rose & Blush",
    description: "Sentuhan romantis rose gold dan keanggunan floral lembut",
    bgGradient: "linear-gradient(180deg, #1c1517 0%, #120e10 100%)",
    bgColor: "#140f11",
    borderColor: "#E0A899",
    accentColor: "#F5CEBE",
    textColor: "#FFF0EB",
    secondaryTextColor: "#C8897A",
    headerStyle: "flourish",
    previewClass: "border-rose-300/50 bg-stone-900",
  },
  {
    id: "botanical_sage",
    name: "Botanical Sage & Forest",
    description: "Keindahan alam dengan nuansa sage green dan emas alami",
    bgGradient: "linear-gradient(180deg, #111a15 0%, #0a110d 100%)",
    bgColor: "#0d1410",
    borderColor: "#A3B899",
    accentColor: "#D6E5D0",
    textColor: "#F1F7EF",
    secondaryTextColor: "#8A9F80",
    headerStyle: "botanical",
    previewClass: "border-emerald-300/50 bg-stone-900",
  },
  {
    id: "midnight_star",
    name: "Midnight Celestial Star",
    description: "Malam berbintang dengan kilau emas dan safir mendalam",
    bgGradient: "linear-gradient(180deg, #0d1322 0%, #060911 100%)",
    bgColor: "#080c16",
    borderColor: "#DFC27D",
    accentColor: "#FFE6A3",
    textColor: "#F5F8FF",
    secondaryTextColor: "#8CA2D4",
    headerStyle: "ornament",
    previewClass: "border-indigo-400/50 bg-stone-900",
  },
  {
    id: "minimal_ivory",
    name: "Timeless Ivory & Noir",
    description: "Kemurnian ivory bersih dengan bingkai tipis super modern",
    bgGradient: "linear-gradient(180deg, #FAF7F2 0%, #F5EFEB 100%)",
    bgColor: "#FAF7F2",
    borderColor: "#303030",
    accentColor: "#1A1A1A",
    textColor: "#1A1A1A",
    secondaryTextColor: "#6B655D",
    headerStyle: "minimal",
    previewClass: "border-stone-400 bg-stone-100",
  },
];

export const PHOTO_FILTERS: CameraFilter[] = [
  {
    id: "normal",
    name: "Natural Beauty",
    css: "none",
    desc: "Warna alami asli kamera tanpa perubahan",
    emoji: "✨",
  },
  {
    id: "soft_glow",
    name: "Bridal Soft Glow",
    css: "contrast(1.05) brightness(1.1) saturate(1.15)",
    desc: "Kulit bercahaya halus dan cerah menawan khas pengantin",
    emoji: "💫",
  },
  {
    id: "warm_vintage",
    name: "Warm Romance",
    css: "sepia(0.28) contrast(1.08) brightness(1.04) saturate(1.18)",
    desc: "Nuansa senja keemasan yang hangat dan romantis",
    emoji: "🌅",
  },
  {
    id: "portra",
    name: "Analog Portra Film",
    css: "contrast(1.15) saturate(1.28) brightness(1.05) sepia(0.08)",
    desc: "Warna film legendaris dengan skin tone sangat flattering",
    emoji: "🎞️",
  },
  {
    id: "noir",
    name: "Classic Noir B&W",
    css: "grayscale(1) contrast(1.28) brightness(1.02)",
    desc: "Monokrom klasik abadi nan elegan dengan kontras mewah",
    emoji: "🖤",
  },
  {
    id: "cool_cinema",
    name: "Cool Cinematic",
    css: "contrast(1.12) hue-rotate(185deg) saturate(0.92)",
    desc: "Sentuhan dingin modern sinematik",
    emoji: "❄️",
  },
  {
    id: "sepia_romance",
    name: "Antique Sepia",
    css: "sepia(0.6) contrast(1.12) brightness(0.98) saturate(1.1)",
    desc: "Nostalgia foto tempo dulu yang anggun",
    emoji: "📜",
  },
];

export const DEFAULT_FRAME_SLOTS: import("./types").FrameSlot[] = [
  {
    id: "slot_1",
    name: "Desain Bingkai 1",
    layoutId: "3x1",
    presetThemeId: "royal_gold",
  },
  {
    id: "slot_2",
    name: "Desain Bingkai 2",
    layoutId: "3x1",
    presetThemeId: "rose_floral",
  },
  {
    id: "slot_3",
    name: "Desain Bingkai 3",
    layoutId: "3x1",
    presetThemeId: "minimal_ivory",
  },
];
